config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to:"tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # validates :title, :details, :completed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(strong_task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(strong_task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private
  # anti hacker form protection
  def strong_task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label "Completed" %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>TASK MANAGER</h2>
<p>Click on the Task that you want to edit</p>

<ul>
<% @tasks.each do |task| %>
<li>
  <% if task.completed == true  %>
  <i class="fa fa-check-square-o" aria-hidden="true"></i>
  <%else  %>
  <i class="fa fa-square-o" aria-hidden="true"></i>
  <% end %>
  <%= link_to task.title, task_path(task) %></li>
<% end %>
</ul>



<%= link_to "Add new task", tasks_new_path  %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>



<%#= simple_form_for @task do |f| %>
  <%#= f.input :title %>
  <%#= f.input :details %>
  <%#= f.button :submit %>
<%# end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><% if @task.completed == true  %>
  <i class="fa fa-check-square-o" aria-hidden="true"></i>
  <%else  %>
  <i class="fa fa-square-o" aria-hidden="true"></i>
  <% end %>Completed</p>



<%= link_to "Edit this Task", task_edit_path(@task) %>
<%= link_to "Go back to overview", tasks_path  %>
<%= link_to "Delete this Task", task_path(@task), method: :delete,
data: {confirm: 'Are you sure you want to delete this task?'}  %>